;; -*- lexical-binding: t -*-
(tool-bar-mode -1)
(set-frame-font "Inconsolata 18")
(package-initialize)
(require 'vertico)
(vertico-mode)
(require 'consult)
(require 'which-key)
(which-key-mode)
(setq project-list-file "~/.emacs.d/var/project.eld")
(require 'consult-project-extra)
(setopt consult-project-function #'consult-project-extra-project-fn)
(keymap-set project-prefix-map "f" #'consult-project-extra-find)
(keymap-set project-prefix-map "b" #'consult-project-extra-buffer)
