(setq treesit-extra-load-path `(,(my/put-this-in-var "tree-sitter")))
(setq treesit-language-source-alist
 '((ada "https://github.com/briot/tree-sitter-ada")
   (bash "https://github.com/tree-sitter/tree-sitter-bash")
   (c "https://github.com/tree-sitter/tree-sitter-c")
   (c++ "https://github.com/tree-sitter/tree-sitter-cpp")
   (clojure "https://github.com/sogaiu/tree-sitter-clojure")
   (cmake "https://github.com/uyha/tree-sitter-cmake")
   (common-lisp "https://github.com/theHamsta/tree-sitter-commonlisp")
   (css "https://github.com/tree-sitter/tree-sitter-css")
   (elixir "https://github.com/elixir-lang/tree-sitter-elixir")
   (elisp "https://github.com/Wilfred/tree-sitter-elisp")
   (erlang "https://github.com/WhatsApp/tree-sitter-erlang/")
   (fennel "https://github.com/travonted/tree-sitter-fennel")
   (go "https://github.com/tree-sitter/tree-sitter-go")
   (haskell "https://github.com/tree-sitter/tree-sitter-haskell")
   (html "https://github.com/tree-sitter/tree-sitter-html")
   (json "https://github.com/tree-sitter/tree-sitter-json")
   (latex "https://github.com/latex-lsp/tree-sitter-latex")
   (lua "https://github.com/MunifTanjim/tree-sitter-lua")
   (make "https://github.com/alemuller/tree-sitter-make")
   (markdown "https://github.com/ikatyang/tree-sitter-markdown")
   (nim "https://github.com/alaviss/tree-sitter-nim")
   (objective-c "https://github.com/jiyee/tree-sitter-objc")
   (ocaml "https://github.com/tree-sitter/tree-sitter-ocaml")
   (perl "https://github.com/ganezdragon/tree-sitter-perl")
   (python "https://github.com/tree-sitter/tree-sitter-python")
   (racket "https://github.com/6cdh/tree-sitter-racket")
   (ruby "https://github.com/tree-sitter/tree-sitter-ruby")
   (rust "https://github.com/tree-sitter/tree-sitter-rust")
   (scheme "https://github.com/6cdh/tree-sitter-scheme")
   (yaml "https://github.com/ikatyang/tree-sitter-yaml")))

(mapc #'treesit-install-language-grammar (mapcar #'car treesit-language-source-alist))
